### ISSUE TITLE
Please adhere to semantic versioning

### ISSUE THREAD

**Issue by Sander-Toonen** [harrison-ifeanyichukwu/php-feed-parser#1]
Commit 68f56730a92decb8f196d7b15470483071f48060 removed a public method "setDefaultLanguage" that was even listed in the projects documentation. Removing this is an incompatible change. Users do not expect a BC-breaking change when you only increase the patch-part of the version number. 

According to [semantic versioning](https://semver.org/) this should have resulted in an increase of the major-part of the version number. Would you please be so kind to adhere to this standard in the future?

**Comment by teclone** [comment]
@Sander-Toonen , thanks for reporting, somehow i missed this. been almost 3 years now, 😂

**Comment by teclone** [comment]
closing issue now
